### ISSUE TITLE
[BUG] $ is not a function after upgrading to 0.11.0

### ISSUE THREAD

**Issue by DavidGolodetsky** [vuestorefront/storefront-ui#1986]
**Describe the bug**
I've upgraded SFui version to the latest `^0.11.0-rc.1` and I see such an error in the console. Looks like it happens on build time:
![image](https://user-images.githubusercontent.com/32278933/131678491-b00ea7bc-13bb-4557-aecf-39d096729ef5.png)

**Comment by Baroshem** [comment]
Hi @DavidGolodetsky 

Thanks for raising that issue. We encountered it in our different project but we thought it was caused but something else. We will work on a fix asap.

**Comment by DavidGolodetsky** [comment]
Strange, I've tried to reproduce it today in the same brunch and it worked out just fine. So I'm closing the issue cause I can't reproduce
